### ISSUE TITLE
Add support for onchip temperature

### ISSUE THREAD

**Issue by tuupola** [tuupola/micropython-mpu9250#1]
Should look something like:

```python
from machine import I2C, Pin
from mpu9250 import MPU9250

i2c = I2C(scl=Pin(22), sda=Pin(21))
sensor = MPU9250(i2c)

print(sensor.temperature)
```

**Comment by vvkuryshev** [comment]
Hello, Mika!

Great project. It works on esp8266 (I use acceleration and rotation measurement). But in fact temperature is not added to mpu9250 module.

**Comment by tuupola** [comment]
Yeah temperature is still on TODO list. I should pay attention to this library again in the near future.
