### ISSUE TITLE
ImportError : cannot load module i2C

### ISSUE THREAD

**Issue by jiamingbacon** [tuupola/micropython-mpu9250#14]
tried using the test code on the readme, but i get this error... Anyway to fix this ? 
Command Im using is micropython test.py

**Comment by tuupola** [comment]
If I understand correctly you are using UNIX port of MicroPython. That port does not support I2C.

**Comment by jiamingbacon** [comment]
yes i am, beause im using raspberry pi.. i see.. thank you !

**Comment by tuupola** [comment]
One of the cheapest options to try would be a ESP32 dev board. They only cost few dollars and can run MicroPython. Those are what I personally mostly use.
