### ISSUE TITLE
Using the library for Microbit

### ISSUE THREAD

**Issue by Essalsolami** [tuupola/micropython-mpu9250#22]
Hi,

Im using Microbit MU online editor. Could i use the library for the microbit. If, yes how does it work plz?

Thank you

**Comment by tuupola** [comment]
I do not know anything about Microbit or the editor you mentioned. But if Microbit supports Micropython I do not see any reason why not.

**Comment by Essalsolami** [comment]
Yes Microbit support Micropython. I will try it
