### ISSUE TITLE
MPU-9250 AK893 is not detected

### ISSUE THREAD

**Issue by pkoprov** [tuupola/micropython-mpu9250#24]
I am using MPU9250 that has a name on it "MPU-9250/6500" and when I run the instance of MPU6500 it works great, but when I run an instance of AK893 it chows an error. and the problem is that I cannot see the magnetometer even when I scan the I2C. Do you know how to find the AK893 or how to connect it to Pi?

**Comment by Robotayylien** [comment]
Following, same problem

**Comment by pkoprov** [comment]
I found out that the MPU-9250 I used is fake. It is basically MPU6500
