### ISSUE TITLE
AK8963 - [Errno 5] EIO

### ISSUE THREAD

**Issue by serdaraltin** [tuupola/micropython-mpu9250#26]
I am using sensor model MPU9250 + BMP280 and I cannot read the magnetometer sensor.
I can read the data of all other sensors, but the sensor named AK8963 gives the error in the picture.
![2022-11-12_02-33](https://user-images.githubusercontent.com/43209941/201444304-0a8d3d6e-6103-4014-ae96-16f8001e62eb.png)
![2022-11-12_02-35](https://user-images.githubusercontent.com/43209941/201444439-c0d6b38c-7786-48e1-a8be-301f41b4eff4.png)

The sensor I use:
![MPU9250-BMP280](https://user-images.githubusercontent.com/43209941/201444897-3e04d067-81e4-403e-9195-2611d731c26e.jpg)

i2c Configuration:
![2022-11-12_02-44](https://user-images.githubusercontent.com/43209941/201445057-5dd3559a-e531-44e8-8f1d-409b4860641e.png)

i2c Scan Result:
![2022-11-12_02-39](https://user-images.githubusercontent.com/43209941/201444823-32353313-bf12-4ff2-81df-00e6b17ce50c.png)

Thanks

**Comment by tuupola** [comment]
The `i2c.scan()` finds `104` ie `0x68` which is default i2c address for MPU-6500 and `118` ie `0x76` which is default i2c address for BME280.

**Comment by serdaraltin** [comment]
When I turn off data reading from AK8963 sensor other sensors work fine.
Why is this so?
![2022-11-12_15-10_1](https://user-images.githubusercontent.com/43209941/201473299-7f40d945-8335-4edf-9e04-d43c29987006.png)
![2022-11-12_15-10_2](https://user-images.githubusercontent.com/43209941/201473315-4a3705b9-8ab3-4639-8d17-29ad637fd525.png)
![2022-11-12_15-10](https://user-images.githubusercontent.com/43209941/201473302-88fa40fb-10cc-4139-983a-b5520f7fa738.png)

**Comment by tuupola** [comment]
There is no AK8963 in the i2c bus. There is only BME280 and MPU-6500. So my guess is that your sensor is not MPU-9250 but a plain MPU-6500 instead.

MPU-9250 is a System in Package (SiP) which combines two chips: MPU-6500 and AK8963.
